---
abstract: 'access MobileMe iPhone stuffs from Perl'
author:
  - 'Michael Greb <michael@thegrebs.com>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.091940'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-MobileMe
requires:
  JSON: 2.00
  Test::More: 0
  WWW::Mechanize: 0
resources:
  repository: http://git.thegrebs.com/git/WebService-MobileMe
version: 0.001
